# Generated by Django 4.2.1 on 2023-06-18 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='number',
            new_name='phone_number',
        ),
    ]
