# Generated by Django 4.2.1 on 2023-06-18 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_number_profile_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MapUserContact',
        ),
    ]
